name: RunJmeterScript

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: setup-jmeter
        run: |
          sudo apt-get update
          sudo apt install curl -y
          sudo apt install -y default-jdk
          wget https://dlcdn.apache.org//jmeter/binaries/apache-jmeter-5.6.2.tgz
          sudo tar -xvf apache-jmeter-5.6.2.tgz
          
          
      - name: Obtain Jmeter Version
        run: |
          cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/bin
          ./jmeter.sh --version
      - name: Install cmd line runner
        run: |
           cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/lib
           sudo curl -O https://repo1.maven.org/maven2/kg/apc/cmdrunner/2.2.1/cmdrunner-2.2.1.jar
      - name: Install plugins manager
        run: |
           cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/lib/ext
           sudo curl -O https://repo1.maven.org/maven2/kg/apc/jmeter-plugins-manager/1.6/jmeter-plugins-manager-1.6.jar
           
      - name: Install plugins 
        run: |
           cd $GITHUB_WORKSPACE/apache-jmeter-5.6.2/lib
           sudo java  -jar cmdrunner-2.2.1.jar --tool org.jmeterplugins.repository.PluginManagerCMD install-all-except jpgc-hadoop,jpgc-oauth,ulp-jmeter-autocorrelator-plugin,ulp-jmeter-videostreaming-plugin,ulp-jmeter-gwt-plugin,tilln-iso8583
           
      - name: copy jmx file to bin folder   
        run: |
           ls $GITHUB_WORKSPACE/
           pwd 
